"""
Safe cleanup of test artifacts from dataset_anonymizer while preserving pipeline structure.

Removes synthetic test images, temp batches, backups, test logs/reports, and stale lock files.
Never touches core scripts, config, or operational source files.

Run from project root:
    python -m scripts.cleanup_test_files
    python -m scripts.cleanup_test_files --yes --empty-input-raw --empty-final-clean
    python -m scripts.cleanup_test_files --preview   # show plan only, no deletions
"""

from __future__ import annotations

import argparse
import fnmatch
import hashlib
import json
import os
import shutil
import stat
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, List, Optional, Sequence

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.utils import load_config, resolve_log_artifacts, resolve_pipeline_paths, setup_project_folders

# ---------------------------------------------------------------------------
# Protected — never delete
# ---------------------------------------------------------------------------

PROTECTED_RELATIVE = frozenset(
    {
        "scripts",
        "config.yaml",
        "README.md",
        "requirements.txt",
        "Dockerfile",
        "docker-compose.yml",
        ".env",
        "security_hardening.py",
        "rclone_integration.py",
        "app.py",
        "tests",
        "vendor",
        "models",
        "docs",
        "config",
        "templates",
        "static",
    }
)

PROTECTED_GLOBS = ("*.py",)  # core Python at project root only — never bulk-delete

# SyntheticPrefab test image basename patterns (seeded by validation / benchmark scripts)
DEFAULT_TEST_IMAGE_PATTERNS: tuple[str, ...] = (
    "gpu_rt_*",
    "perf_*",
    "prod_test_*",
    "prod_val_*",
    "final_val_*",
    "scale_*",
    "roundtrip_*",
    "sample_*",
)

# Reports generated by test / benchmark runs (safe to remove before production)
TEST_REPORT_FILES: tuple[str, ...] = (
    "processed_manifest.json",
    "master_summary.csv",
    "master_summary.pdf",
    "gpu_benchmark.json",
    "performance_report.md",
)

REQUIRED_FOLDERS: tuple[str, ...] = (
    "input_raw",
    "temp_processed",
    "final_clean",
    "quarantine",
    "manual_review",
    "logs",
    "logs/batch_summaries",
    "reports",
    "models",
    "scripts",
)

IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp", ".bmp", ".tif", ".tiff"}


@dataclass
class CleanupSummary:
    deleted_files: int = 0
    deleted_dirs: int = 0
    cleared_audit_entries: int = 0
    preserved_audit_entries: int = 0
    paths_removed: List[str] = field(default_factory=list)
    errors: List[str] = field(default_factory=list)

    def note_file(self, path: Path) -> None:
        self.deleted_files += 1
        if len(self.paths_removed) < 200:
            self.paths_removed.append(str(path))

    def note_dir(self, path: Path) -> None:
        self.deleted_dirs += 1
        if len(self.paths_removed) < 200:
            self.paths_removed.append(f"{path}/")


def _is_protected(path: Path, project_root: Path) -> bool:
    """Return True if path must not be deleted."""
    try:
        rel = path.resolve().relative_to(project_root.resolve())
    except ValueError:
        return True
    parts = rel.parts
    if not parts:
        return True
    if parts[0] in PROTECTED_RELATIVE:
        return True
    if len(parts) == 1 and any(fnmatch.fnmatch(parts[0], g) for g in PROTECTED_GLOBS):
        return True
    return False


def _matches_test_image(name: str, patterns: Sequence[str]) -> bool:
    stem = Path(name).stem
    for pat in patterns:
        if fnmatch.fnmatch(name, pat) or fnmatch.fnmatch(stem, pat):
            return True
    return False


def _is_test_sidecar(path: Path, patterns: Sequence[str]) -> bool:
    if path.suffix.lower() == ".json":
        return _matches_test_image(path.stem, patterns)
    return _matches_test_image(path.name, patterns)


def _confirm(prompt: str, *, auto_yes: bool) -> bool:
    if auto_yes:
        print(f"{prompt} [auto-yes]")
        return True
    try:
        answer = input(f"{prompt} [y/N]: ").strip().lower()
    except EOFError:
        print(" (no input - aborted)")
        return False
    return answer in ("y", "yes")


def _chmod_writable(path: str) -> None:
    try:
        os.chmod(path, stat.S_IWRITE | stat.S_IREAD)
    except OSError:
        pass


def _secure_rmtree(path: Path, summary: CleanupSummary, project_root: Path) -> None:
    if not path.exists():
        return
    if _is_protected(path, project_root):
        summary.errors.append(f"skipped protected path: {path}")
        return

    def _onerror(func, p, _exc_info) -> None:
        _chmod_writable(p)
        try:
            func(p)
        except OSError:
            pass

    shutil.rmtree(path, onerror=_onerror)
    if path.exists():
        # Last resort: clear files then retry empty dirs (OneDrive / Windows locks)
        for root, dirs, files in os.walk(path, topdown=False):
            for name in files:
                fp = os.path.join(root, name)
                _chmod_writable(fp)
                try:
                    os.remove(fp)
                except OSError:
                    pass
            for name in dirs:
                dp = os.path.join(root, name)
                _chmod_writable(dp)
                try:
                    os.rmdir(dp)
                except OSError:
                    pass
        try:
            path.rmdir()
        except OSError:
            remaining = sum(1 for _ in path.rglob("*"))
            if remaining:
                summary.errors.append(f"failed to remove directory: {path} ({remaining} items remain)")
    else:
        summary.note_dir(path)


def _secure_unlink(path: Path, summary: CleanupSummary, project_root: Path) -> None:
    if not path.is_file():
        return
    if _is_protected(path, project_root):
        summary.errors.append(f"skipped protected file: {path}")
        return
    try:
        path.unlink(missing_ok=True)
        summary.note_file(path)
    except OSError as exc:
        summary.errors.append(f"failed to remove {path}: {exc}")


def _clear_directory_contents(
    directory: Path,
    summary: CleanupSummary,
    project_root: Path,
    *,
    keep_gitkeep: bool = True,
    name_filter: Optional[Callable[[str], bool]] = None,
) -> None:
    if not directory.is_dir():
        return
    for item in list(directory.iterdir()):
        if keep_gitkeep and item.name == ".gitkeep":
            continue
        if name_filter is not None and not name_filter(item.name):
            continue
        if item.is_dir():
            _secure_rmtree(item, summary, project_root)
        else:
            _secure_unlink(item, summary, project_root)


def _clean_audit_json(
    audit_path: Path,
    patterns: Sequence[str],
    summary: CleanupSummary,
    *,
    reset_if_all_test: bool = True,
) -> None:
    if not audit_path.is_file():
        return
    try:
        raw = audit_path.read_text(encoding="utf-8").strip()
        entries = json.loads(raw) if raw else []
    except (json.JSONDecodeError, OSError) as exc:
        summary.errors.append(f"could not read {audit_path}: {exc}")
        return
    if not isinstance(entries, list):
        summary.errors.append(f"unexpected audit format in {audit_path}")
        return

    kept: list = []
    removed = 0
    for entry in entries:
        if not isinstance(entry, dict):
            kept.append(entry)
            continue
        image = str(entry.get("image", ""))
        if _matches_test_image(image, patterns):
            removed += 1
        else:
            kept.append(entry)

    summary.cleared_audit_entries = removed
    summary.preserved_audit_entries = len(kept)

    if reset_if_all_test and removed > 0 and len(kept) == 0:
        audit_path.write_text("[]\n", encoding="utf-8")
        print(f"  audit: cleared all {removed} test entries -> []")
    elif removed > 0:
        audit_path.write_text(json.dumps(kept, indent=2) + "\n", encoding="utf-8")
        print(f"  audit: removed {removed} test entries, kept {len(kept)} production entries")
    else:
        print(f"  audit: no test entries found ({len(kept)} entries preserved unchanged)")


def _find_lock_files(project_root: Path) -> List[Path]:
    locks: List[Path] = []
    for path in project_root.rglob("*.lock"):
        if _is_protected(path, project_root):
            continue
        if ".venv" in path.parts or "vendor" in path.parts:
            continue
        locks.append(path)
    for path in project_root.rglob("*.processing.lock"):
        if _is_protected(path, project_root):
            continue
        if ".venv" in path.parts:
            continue
        locks.append(path)
    return locks


def _collect_test_images(directory: Path, patterns: Sequence[str]) -> List[Path]:
    if not directory.is_dir():
        return []
    found: List[Path] = []
    for path in directory.rglob("*"):
        if not path.is_file():
            continue
        if path.name == ".gitkeep":
            continue
        if path.suffix.lower() in IMAGE_EXTENSIONS or path.suffix.lower() == ".json":
            if _is_test_sidecar(path, patterns):
                found.append(path)
    return found


def _preview_plan(
    project_root: Path,
    paths: dict,
    patterns: Sequence[str],
    *,
    empty_input_raw: bool,
    empty_final_clean: bool,
) -> None:
    print("\n=== Cleanup preview ===\n")
    buckets = [
        ("temp_processed/", paths["temp_processed"]),
        ("backups/", project_root / "backups"),
        ("quarantine/b2_transfer_failures/", paths["quarantine"] / "b2_transfer_failures"),
    ]
    for label, p in buckets:
        n = sum(1 for _ in p.rglob("*") if _.is_file()) if p.exists() else 0
        print(f"  {label}: {n} file(s)")

    logfile, batch_dir = resolve_log_artifacts(project_root, paths["logs"], load_config(project_root / "config.yaml"))
    log_files = [logfile, paths["logs"] / "monitoring.jsonl"]
    log_count = sum(1 for f in log_files if f.is_file())
    log_count += sum(1 for _ in batch_dir.glob("*") if _.is_file()) if batch_dir.is_dir() else 0
    print(f"  logs/ (files only, keep folders): {log_count} file(s)")

    reports_dir = paths["reports"]
    rep_count = sum(1 for name in TEST_REPORT_FILES if (reports_dir / name).is_file())
    print(f"  reports/ test artifacts: {rep_count} file(s)")

    locks = _find_lock_files(project_root)
    print(f"  *.lock / *.processing.lock: {len(locks)} file(s)")

    test_input = _collect_test_images(paths["input_raw"], patterns)
    all_input = [p for p in paths["input_raw"].rglob("*") if p.is_file() and p.name != ".gitkeep"]
    if empty_input_raw:
        print(f"  input_raw/: ALL {len(all_input)} image(s) (--empty-input-raw)")
    else:
        print(f"  input_raw/ test images: {len(test_input)} / {len(all_input)} total")

    test_final = _collect_test_images(paths["final_clean"], patterns)
    all_final = [p for p in paths["final_clean"].rglob("*") if p.is_file() and p.name != ".gitkeep"]
    if empty_final_clean:
        print(f"  final_clean/: ALL {len(all_final)} file(s) (--empty-final-clean)")
    else:
        print(f"  final_clean/ test outputs: {len(test_final)} / {len(all_final)} total")

    mr_test = _collect_test_images(paths["manual_review"], patterns)
    print(f"  manual_review/ test files: {len(mr_test)} file(s)")
    print()


def run_cleanup(
    *,
    project_root: Path | None = None,
    auto_yes: bool = False,
    preview_only: bool = False,
    empty_input_raw: bool = False,
    empty_final_clean: bool = False,
    test_patterns: Sequence[str] | None = None,
    run_pipeline_dry_run: bool = True,
) -> CleanupSummary:
    project_root = (project_root or ROOT).resolve()
    cfg_path = project_root / "config.yaml"
    if not cfg_path.is_file():
        raise FileNotFoundError(f"config.yaml not found at {cfg_path}")

    config_before = cfg_path.read_bytes()
    cfg = load_config(cfg_path)
    paths = resolve_pipeline_paths(project_root, cfg)
    patterns = tuple(test_patterns or DEFAULT_TEST_IMAGE_PATTERNS)

    _preview_plan(
        project_root,
        paths,
        patterns,
        empty_input_raw=empty_input_raw,
        empty_final_clean=empty_final_clean,
    )

    if preview_only:
        print("Preview only — no files deleted.")
        return CleanupSummary()

    if not _confirm(
        "This will delete test images, temp batches, backups, and test logs/reports. Continue?",
        auto_yes=auto_yes,
    ):
        print("Aborted.")
        return CleanupSummary()

    if empty_input_raw:
        if not _confirm(
            "Empty ALL files in input_raw/ (not just test patterns). Continue?",
            auto_yes=auto_yes,
        ):
            empty_input_raw = False

    if empty_final_clean:
        if not _confirm(
            "Empty ALL files in final_clean/ (clean slate). Continue?",
            auto_yes=auto_yes,
        ):
            empty_final_clean = False

    summary = CleanupSummary()

    # temp_processed — clear all batch work, keep folder
    if paths["temp_processed"].is_dir():
        for child in list(paths["temp_processed"].iterdir()):
            if child.is_dir():
                _secure_rmtree(child, summary, project_root)
            else:
                _secure_unlink(child, summary, project_root)
    paths["temp_processed"].mkdir(parents=True, exist_ok=True)

    # backups — remove entire directory (recreated on next backup_manifests run)
    if (project_root / "backups").exists():
        _secure_rmtree(project_root / "backups", summary, project_root)

    # quarantine/b2_transfer_failures
    _secure_rmtree(paths["quarantine"] / "b2_transfer_failures", summary, project_root)

    # quarantine test artifacts (keep .gitkeep + ingest_rejects structure if non-test)
    def _clean_inventory_dir(directory: Path) -> None:
        if not directory.is_dir():
            return
        for item in list(directory.iterdir()):
            if item.name in (".gitkeep", "ingest_rejects"):
                if item.is_dir() and item.name == "ingest_rejects":
                    _clear_directory_contents(item, summary, project_root, keep_gitkeep=True)
                continue
            if item.is_dir():
                _clear_directory_contents(
                    item,
                    summary,
                    project_root,
                    keep_gitkeep=True,
                    name_filter=lambda n: _matches_test_image(n, patterns) or n.endswith(".json"),
                )
                if not any(item.iterdir()) or all(x.name == ".gitkeep" for x in item.iterdir()):
                    pass
            elif _is_test_sidecar(item, patterns) or item.suffix.lower() == ".lock":
                _secure_unlink(item, summary, project_root)

    _clean_inventory_dir(paths["quarantine"])

    # manual_review — only test files
    mr_test = _collect_test_images(paths["manual_review"], patterns)
    if mr_test:
        for path in mr_test:
            _secure_unlink(path, summary, project_root)
        # remove empty subdirs
        for sub in sorted(paths["manual_review"].rglob("*"), reverse=True):
            if sub.is_dir() and sub.name != ".gitkeep" and not any(sub.iterdir()):
                _secure_rmtree(sub, summary, project_root)

    # logs — delete files, keep folders
    logfile, batch_summary_dir = resolve_log_artifacts(project_root, paths["logs"], cfg)
    for log_path in (logfile, paths["logs"] / "monitoring.jsonl"):
        if log_path.is_file() and log_path.stat().st_size > 0:
            log_path.write_text("", encoding="utf-8")
            summary.note_file(log_path)
    if batch_summary_dir.is_dir():
        _clear_directory_contents(batch_summary_dir, summary, project_root, keep_gitkeep=False)

    # reports — test artifacts + selective audit cleanup
    reports_dir = paths["reports"]
    for name in TEST_REPORT_FILES:
        _secure_unlink(reports_dir / name, summary, project_root)

    reports_block = cfg.get("reports") if isinstance(cfg.get("reports"), dict) else {}
    audit_rel = str(reports_block.get("audit_json", "reports/anonymization_audit.json"))
    audit_path = project_root / audit_rel if not Path(audit_rel).is_absolute() else Path(audit_rel)
    if not audit_path.is_file() and audit_rel.startswith("reports/"):
        audit_path = reports_dir / Path(audit_rel).name
    _clean_audit_json(audit_path, patterns, summary)

    processed_manifest = reports_dir / "processed_manifest.json"
    sec_processed = (cfg.get("security") or {}).get("processed_manifest")
    if sec_processed:
        alt = project_root / str(sec_processed)
        if alt.is_file():
            _secure_unlink(alt, summary, project_root)
    _secure_unlink(processed_manifest, summary, project_root)

    # lock files
    for lock in _find_lock_files(project_root):
        _secure_unlink(lock, summary, project_root)

    # input_raw images
    if empty_input_raw:
        _clear_directory_contents(
            paths["input_raw"],
            summary,
            project_root,
            keep_gitkeep=True,
        )
    else:
        for path in _collect_test_images(paths["input_raw"], patterns):
            _secure_unlink(path, summary, project_root)

    # final_clean outputs
    if empty_final_clean:
        _clear_directory_contents(
            paths["final_clean"],
            summary,
            project_root,
            keep_gitkeep=True,
        )
    else:
        for path in _collect_test_images(paths["final_clean"], patterns):
            _secure_unlink(path, summary, project_root)

    # recreate operational folder tree
    setup_project_folders(project_root, cfg)

    # verify config untouched
    config_after = cfg_path.read_bytes()
    if config_before != config_after:
        summary.errors.append("WARNING: config.yaml was modified during cleanup (unexpected)")

    _print_summary(summary, project_root, config_before)
    _verify_structure(project_root)

    if run_pipeline_dry_run:
        _run_pipeline_dry_run(project_root)

    return summary


def _print_summary(summary: CleanupSummary, project_root: Path, config_before: bytes) -> None:
    print("\n=== Cleanup summary ===")
    print(f"  Files removed:  {summary.deleted_files}")
    print(f"  Dirs removed:   {summary.deleted_dirs}")
    print(f"  Audit entries cleared: {summary.cleared_audit_entries}")
    print(f"  Audit entries kept:    {summary.preserved_audit_entries}")
    if summary.paths_removed:
        print("  Sample paths:")
        for p in summary.paths_removed[:25]:
            print(f"    - {p}")
        if len(summary.paths_removed) >= 25:
            print("    ...")
    if summary.errors:
        print("  Errors / warnings:")
        for err in summary.errors:
            print(f"    ! {err}")
    digest = hashlib.sha256(config_before).hexdigest()[:12]
    print(f"  config.yaml SHA256 prefix: {digest} (unchanged)")


def _verify_structure(project_root: Path) -> None:
    print("\n=== Structure verification ===")
    ok = True
    for rel in REQUIRED_FOLDERS:
        p = project_root / rel
        exists = p.exists()
        status = "OK" if exists else "MISSING"
        print(f"  [{status}] {rel}/")
        if not exists:
            ok = False
    core_files = ["config.yaml", "README.md", "requirements.txt", "scripts/main_pipeline.py"]
    for rel in core_files:
        p = project_root / rel
        exists = p.is_file()
        status = "OK" if exists else "MISSING"
        print(f"  [{status}] {rel}")
        if not exists:
            ok = False
    if ok:
        print("\nPipeline structure intact - ready for full 37k image runs.")
    else:
        print("\nWARNING: Some required paths are missing — run setup_project_folders or restore from git.")


def _run_pipeline_dry_run(project_root: Path) -> None:
    print("\n=== Pipeline dry-run check ===")
    try:
        from scripts.main_pipeline import run_pipeline

        result = run_pipeline(
            project_root=project_root,
            config_path=project_root / "config.yaml",
            dry_run=True,
            max_images=5,
        )
        plan = result.get("plan") or {}
        print(f"  dry_run: {result.get('dry_run')}")
        print(f"  pending_images: {plan.get('pending_images')}")
        print(f"  batch_size: {plan.get('batch_size')}")
        print(f"  gpu_device: {plan.get('gpu_device')}")
        sample = result.get("pending_sample") or []
        if sample:
            print(f"  pending_sample: {sample[:5]}")
        print("  Pipeline dry-run PASSED.")
    except Exception as exc:
        print(f"  Pipeline dry-run FAILED: {exc}")
        raise


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Remove test artifacts from dataset_anonymizer (safe, idempotent)."
    )
    parser.add_argument(
        "--yes",
        "-y",
        action="store_true",
        help="Skip confirmation prompts (non-interactive)",
    )
    parser.add_argument(
        "--preview",
        action="store_true",
        help="Show deletion plan only; do not delete anything",
    )
    parser.add_argument(
        "--empty-input-raw",
        action="store_true",
        help="Remove ALL files in input_raw/ (not just test patterns)",
    )
    parser.add_argument(
        "--empty-final-clean",
        action="store_true",
        help="Remove ALL files in final_clean/ (clean slate)",
    )
    parser.add_argument(
        "--project-root",
        type=Path,
        default=ROOT,
        help="Project root (default: auto-detected)",
    )
    parser.add_argument(
        "--skip-dry-run",
        action="store_true",
        help="Skip post-cleanup pipeline dry-run",
    )
    args = parser.parse_args()

    run_cleanup(
        project_root=args.project_root,
        auto_yes=bool(args.yes),
        preview_only=bool(args.preview),
        empty_input_raw=bool(args.empty_input_raw),
        empty_final_clean=bool(args.empty_final_clean),
        run_pipeline_dry_run=not bool(args.skip_dry_run),
    )


if __name__ == "__main__":
    main()
