#!/usr/bin/env python3
"""
Build a clean, GitHub-ready copy of dataset_anonymizer.

Copies the full operational project (code, configs, docs, tests) to a new directory,
omitting virtualenvs, caches, secrets, and testing artifacts. Operational folder
structure is preserved with .gitkeep placeholders where empty.

Run from project root:
    python -m scripts.prepare_github_release
    python -m scripts.prepare_github_release --dest ../dataset_anonymizer_release
    python -m scripts.prepare_github_release --dest ../dataset_anonymizer_release --force
"""

from __future__ import annotations

import argparse
import fnmatch
import os
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterator, Optional, Sequence, Set, Tuple

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.cleanup_testing_artifacts import (  # noqa: E402
    PRODUCTION_BATCH_SUMMARY_RE,
    TEMP_BATCH_DIR_RE,
    _basename_matches_test_markers,
    _is_junk_file,
    _is_production_manifest,
)
from scripts.utils import setup_project_folders  # noqa: E402

# Never copy these top-level names
EXCLUDE_TOP_LEVEL: frozenset[str] = frozenset(
    {
        ".venv",
        "venv",
        "__pycache__",
        ".git",
        ".cursor",
        "backups",
        "ui_validation_run",
        "5.3",
        ".pytest_cache",
        ".mypy_cache",
    }
)

# Root-level paths to never copy (files or dirs)
EXCLUDE_ROOT_NAMES: frozenset[str] = frozenset({"5.3"})

# Never copy these path prefixes (relative)
EXCLUDE_PREFIXES: Tuple[str, ...] = (
    "reports/cleanup_plans/",
)

# Test report files (regenerated by pipeline)
EXCLUDE_REPORT_FILES: frozenset[str] = frozenset(
    {
        "gpu_benchmark.json",
        "performance_report.md",
        "processed_manifest.json",
        "master_summary.csv",
        "master_summary.pdf",
    }
)

OPERATIONAL_DIRS: Tuple[str, ...] = (
    "input_raw",
    "final_clean",
    "quarantine",
    "manual_review",
    "temp_processed",
    "logs",
    "logs/batch_summaries",
    "reports",
    "models",
    "vendor",
    "backups",
)

GITIGNORE_CONTENT = """# Python bytecode / caches
__pycache__/
*.py[cod]
*$py.class
.pytest_cache/
.mypy_cache/
*.egg-info/
dist/
build/

# Virtualenv binaries (large, platform-specific) — structure + lockfile ARE committed
.venv/Lib/site-packages/
.venv/Scripts/python.exe
.venv/Scripts/pythonw.exe
.venv/Scripts/pip*.exe
.venv/Scripts/*.dll
.venv/Include/

# Real secrets override files (never commit production keys)
.env.local
.env.production
.env.*.local

# NOTE: .env in this repo contains MOCK placeholders only (safe to commit as documentation).

# Runtime / local backups
backups/

# IDE
.idea/
.vscode/
*.swp
.DS_Store
Thumbs.db

# Ephemeral pipeline workspace (recreated each run)
temp_processed/*
!temp_processed/.gitkeep

# Optional: uncomment to keep large cleaned datasets out of git (use B2 / LFS instead)
# final_clean/*
# !final_clean/.gitkeep
# input_raw/*
# !input_raw/.gitkeep

# Logs (regenerated)
logs/*.log
logs/*.jsonl
logs/batch_summaries/*.csv

# Local validation scratch
ui_validation_run/
"""

MOCK_ENV_CONTENT = """# =============================================================================
# dataset_anonymizer — environment variables (MOCK / PLACEHOLDER VALUES ONLY)
# =============================================================================
# This file documents every variable the pipeline expects. Replace ALL mock values
# before running real B2 transfers. Do not push real keys to a public repository.
# =============================================================================

# --- Backblaze B2 (required for ingest/export) --------------------------------
B2_KEY_ID=000000000000000000000000
B2_READONLY_KEY=MOCK_B2_READONLY_KEY_32CHARS_MINIMUM_xxxxx
B2_WRITE_KEY=MOCK_B2_WRITE_KEY_32CHARS_MINIMUM_xxxxx
B2_READONLY_BUCKET=mock-source-bucket-name
B2_WRITE_BUCKET=mock-dest-bucket-name
B2_INGEST_REMOTE_PATH=datasets/raw
B2_EXPORT_REMOTE_PATH=datasets/anonymized

# --- rclone -------------------------------------------------------------------
RCLONE_BINARY=rclone
RCLONE_CONFIG=~/.config/rclone/rclone.conf
# RCLONE_AUTO_CONFIRM=0

# --- rclone crypt (optional) --------------------------------------------------
# RCLONE_CRYPT_PASSWORD=MOCK_CRYPT_PASSWORD_REPLACE_ME
# RCLONE_CRYPT_PASSWORD2=
# RCLONE_CRYPT_SALT=MOCK_CRYPT_SALT_REPLACE_ME

# --- Optional QA / LLM (qa.use_crewai_llm: true) ------------------------------
# OPENAI_API_KEY=sk-MOCK_OPENAI_KEY_REPLACE_ME

# --- GPU / Web UI (optional) ----------------------------------------------------
# CUDA_VISIBLE_DEVICES=0
# FLASK_HOST=127.0.0.1
# FLASK_PORT=5000
"""

ENV_EXAMPLE_CONTENT = MOCK_ENV_CONTENT.replace(
    "MOCK / PLACEHOLDER VALUES ONLY",
    "copy and fill with real secrets locally",
).replace("MOCK_B2_READONLY_KEY_32CHARS_MINIMUM_xxxxx", "").replace(
    "MOCK_B2_WRITE_KEY_32CHARS_MINIMUM_xxxxx", ""
)

VENDOR_README = """# vendor/deep_privacy2

DeepPrivacy2 is **not** vendored in git (large upstream repo).

Clone before running face anonymization on GPU:

```bash
git clone https://github.com/hukkelas/deep_privacy2 vendor/deep_privacy2
```

Then install per upstream docs and `docs/DEPLOY.md`.
"""

GITHUB_PUSH_MD = """# Pushing this repository to GitHub

This folder is a **production-ready copy** of `dataset_anonymizer`:
testing artifacts, virtualenvs, caches, and secrets were excluded.

## 1. Review

```bash
python -m scripts.health_check
python -m scripts.cleanup_testing_artifacts   # dry-run; should show little/nothing
```

## 2. Initialize git (if not already)

```bash
git init
git add .
git status
```

The committed `.env` uses **mock placeholders only** — replace locally before production.

## 3. Commit and push

```bash
git commit -m "Initial production pipeline release"
git branch -M main
git remote add origin https://github.com/YOUR_ORG/dataset_anonymizer.git
git push -u origin main
```

## 4. Large datasets

If `final_clean/` or `input_raw/` contain tens of thousands of files, consider:
- Git LFS for media, or
- Keeping data on Backblaze B2 only (uncomment paths in `.gitignore`)

Never push a `.env` with real B2 keys to a public repo. Use `.env.local` for secrets (gitignored).
"""


VENV_README = """# `.venv` — Python environment (GitHub template)

Mirrors the original `dataset_anonymizer` layout. `Lib/site-packages` is not in git.

## Recreate

```bash
python -m venv .venv
.venv\\Scripts\\activate          # Windows
# source .venv/bin/activate       # Linux/macOS
pip install -r requirements.txt
```

See `requirements-lock.txt` for reference package versions from the dev environment.
"""

VENV_SCRIPTS_README = """# Scripts/

Created by `python -m venv .venv` (activate.bat, Activate.ps1, python.exe, pip.exe on Windows).
"""

VENV_LIB_README = """# Lib/

Populated by `pip install -r requirements.txt` with torch, paddleocr, insightface, flask, etc.
"""


def _write_environment_template(dest_root: Path, src_root: Path) -> None:
    """Add mock .env and .venv documentation tree (no site-packages binaries)."""
    (dest_root / ".env").write_text(MOCK_ENV_CONTENT, encoding="utf-8")
    (dest_root / ".env.example").write_text(ENV_EXAMPLE_CONTENT, encoding="utf-8")

    venv = dest_root / ".venv"
    scripts = venv / "Scripts"
    lib = venv / "Lib"
    scripts.mkdir(parents=True, exist_ok=True)
    lib.mkdir(parents=True, exist_ok=True)

    src_cfg = src_root / ".venv" / "pyvenv.cfg"
    if src_cfg.is_file():
        shutil.copy2(src_cfg, venv / "pyvenv.cfg")
    else:
        (venv / "pyvenv.cfg").write_text(
            "home = (your Python install)\ninclude-system-site-packages = false\nversion = 3.10\n",
            encoding="utf-8",
        )

    (venv / "README.md").write_text(VENV_README, encoding="utf-8")
    (scripts / "README.md").write_text(VENV_SCRIPTS_README, encoding="utf-8")
    (lib / "README.md").write_text(VENV_LIB_README, encoding="utf-8")

    pip_exe = src_root / ".venv" / "Scripts" / "pip.exe"
    lock_path = venv / "requirements-lock.txt"
    if pip_exe.is_file():
        import subprocess

        proc = subprocess.run(
            [str(pip_exe), "freeze"],
            capture_output=True,
            text=True,
            timeout=120,
            check=False,
        )
        if proc.returncode == 0 and proc.stdout.strip():
            lock_path.write_text(proc.stdout.strip() + "\n", encoding="utf-8")
        else:
            lock_path.write_text(
                "# pip freeze failed; install from requirements.txt\n",
                encoding="utf-8",
            )
    else:
        lock_path.write_text(
            "# No source .venv found; run: pip install -r requirements.txt\n",
            encoding="utf-8",
        )


def _should_skip_file(rel_posix: str, name: str) -> Tuple[bool, str]:
    """Return (skip, reason) for a file during copy."""
    if name in (".env", ".env.local", ".env.production") or rel_posix == ".env":
        return True, "secret_env"
    if rel_posix.startswith(".venv/"):
        return True, "venv_template_generated"
    if _is_junk_file(name):
        return True, "junk"
    lower_rel = rel_posix.lower()
    for prefix in EXCLUDE_PREFIXES:
        if lower_rel.startswith(prefix):
            return True, "exclude_prefix"
    parts = rel_posix.split("/")
    if not parts:
        return False, ""
    top = parts[0]
    # reports test outputs
    if top == "reports" and name in EXCLUDE_REPORT_FILES:
        return True, "test_report"
    # input_raw / quarantine / manual_review test seeds
    if top in ("input_raw", "quarantine", "manual_review") and _basename_matches_test_markers(name):
        return True, "test_artifact"
    # final_clean test outputs
    if top == "final_clean":
        if _basename_matches_test_markers(name):
            return True, "test_artifact"
        if name == ".gitkeep":
            return False, ""
    # logs: skip generated logs; keep .gitkeep
    if top == "logs":
        if name == ".gitkeep":
            return False, ""
        if name.endswith((".log", ".jsonl")):
            return True, "generated_log"
        if len(parts) >= 2 and parts[1] == "batch_summaries":
            if PRODUCTION_BATCH_SUMMARY_RE.match(name):
                return True, "batch_summary_regenerable"
            if _basename_matches_test_markers(name):
                return True, "test_artifact"
    # temp_processed: never copy batch workspaces
    if top == "temp_processed":
        if name == ".gitkeep":
            return False, ""
        if parts and TEMP_BATCH_DIR_RE.match(parts[-1] if len(parts) == 1 else parts[0]):
            return True, "temp_batch"
        if len(parts) >= 1 and TEMP_BATCH_DIR_RE.match(parts[0]):
            return True, "inside_batch"
        return True, "temp_ephemeral"
    if top == "backups":
        return True, "backups"
    return False, ""


def _should_skip_dir(rel_posix: str, name: str) -> bool:
    if rel_posix == ".venv" or rel_posix.startswith(".venv/"):
        return True
    if name in EXCLUDE_TOP_LEVEL:
        return True
    if name in ("__pycache__", ".pytest_cache", ".mypy_cache", ".git"):
        return True
    lower = rel_posix.lower()
    for prefix in EXCLUDE_PREFIXES:
        if lower.startswith(prefix):
            return True
    parts = rel_posix.split("/")
    if parts and parts[0] == "temp_processed":
        if TEMP_BATCH_DIR_RE.match(name):
            return True
        if name in ("_source_copies", "_work", "_scratch", "cache", ".cache"):
            return True
    if parts and parts[0] == "backups":
        return True
    return False


def _iter_source_files(src_root: Path) -> Iterator[Tuple[Path, str]]:
    """Yield (absolute_path, relative_posix_path) for files to consider copying."""
    src_root = src_root.resolve()
    for dirpath, dirnames, filenames in os.walk(src_root, topdown=True):
        rel_dir = Path(dirpath).relative_to(src_root)
        rel_dir_posix = rel_dir.as_posix() if rel_dir.parts else ""

        filtered_dirs: list[str] = []
        for d in dirnames:
            child_rel = f"{rel_dir_posix}/{d}" if rel_dir_posix else d
            if _should_skip_dir(child_rel, d):
                continue
            filtered_dirs.append(d)
        dirnames[:] = filtered_dirs

        for fname in filenames:
            rel_posix = f"{rel_dir_posix}/{fname}" if rel_dir_posix else fname
            yield Path(dirpath) / fname, rel_posix


def _write_gitkeep(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)
    gk = path / ".gitkeep"
    if not gk.exists():
        gk.write_text("", encoding="utf-8")


def build_release_copy(
    src_root: Path,
    dest_root: Path,
    *,
    force: bool = False,
) -> dict:
    src_root = src_root.resolve()
    dest_root = dest_root.resolve()

    if dest_root.exists():
        if not force:
            raise FileExistsError(
                f"Destination already exists: {dest_root}\nUse --force to replace."
            )
        shutil.rmtree(dest_root, ignore_errors=True)

    dest_root.mkdir(parents=True, exist_ok=True)

    stats = {
        "files_copied": 0,
        "files_skipped": 0,
        "bytes_copied": 0,
        "skip_reasons": {},
    }

    def _skip_reason(reason: str) -> None:
        stats["files_skipped"] += 1
        stats["skip_reasons"][reason] = stats["skip_reasons"].get(reason, 0) + 1

    for abs_path, rel_posix in _iter_source_files(src_root):
        name = abs_path.name
        if rel_posix in EXCLUDE_ROOT_NAMES or rel_posix.split("/")[0] in EXCLUDE_TOP_LEVEL:
            _skip_reason("exclude_root")
            continue
        skip, reason = _should_skip_file(rel_posix, name)
        if skip:
            _skip_reason(reason)
            continue

        dest_file = dest_root / rel_posix
        dest_file.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(abs_path, dest_file)
        try:
            stats["bytes_copied"] += abs_path.stat().st_size
        except OSError:
            pass
        stats["files_copied"] += 1

    # Ensure operational dirs + gitkeep
    for rel in OPERATIONAL_DIRS:
        _write_gitkeep(dest_root / rel)

    # Scaffold via project helper
    try:
        from scripts.utils import load_config

        cfg = load_config(dest_root / "config.yaml")
        setup_project_folders(dest_root, cfg)
    except Exception:
        setup_project_folders(dest_root, None)

    # GitHub helper files + environment template (.env mock keys, .venv layout)
    (dest_root / ".gitignore").write_text(GITIGNORE_CONTENT, encoding="utf-8")
    _write_environment_template(dest_root, src_root)
    (dest_root / "GITHUB_PUSH.md").write_text(GITHUB_PUSH_MD, encoding="utf-8")
    vendor_dir = dest_root / "vendor"
    vendor_dir.mkdir(parents=True, exist_ok=True)
    (vendor_dir / "README.md").write_text(VENDOR_README, encoding="utf-8")
    if not (vendor_dir / ".gitkeep").exists():
        (vendor_dir / ".gitkeep").write_text("", encoding="utf-8")

    # Empty regenerable reports audit if missing
    audit = dest_root / "reports" / "anonymization_audit.json"
    if not audit.exists():
        audit.parent.mkdir(parents=True, exist_ok=True)
        audit.write_text("[]\n", encoding="utf-8")

    return stats


def main() -> None:
    parser = argparse.ArgumentParser(description="Create a GitHub-ready project copy.")
    parser.add_argument(
        "--dest",
        type=Path,
        default=ROOT.parent / "dataset_anonymizer_release",
        help="Destination directory (default: ../dataset_anonymizer_release)",
    )
    parser.add_argument(
        "--source",
        type=Path,
        default=ROOT,
        help="Source project root",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Replace destination if it exists",
    )
    args = parser.parse_args()

    print(f"Source:      {args.source.resolve()}")
    print(f"Destination: {args.dest.resolve()}")
    print(f"Started:     {datetime.now(timezone.utc).isoformat()}")

    stats = build_release_copy(args.source, args.dest, force=bool(args.force))

    print()
    print("=" * 72)
    print("GitHub release copy ready")
    print("=" * 72)
    print(f"  Files copied:  {stats['files_copied']:,}")
    print(f"  Files skipped: {stats['files_skipped']:,}")
    print(f"  Size copied:   {stats['bytes_copied'] / (1024**2):.2f} MiB")
    if stats["skip_reasons"]:
        print("  Skip breakdown:")
        for reason, count in sorted(stats["skip_reasons"].items(), key=lambda x: -x[1]):
            print(f"    {reason}: {count}")
    print()
    print(f"  Next: cd {args.dest.resolve()}")
    print("        python -m scripts.health_check")
    print("        See GITHUB_PUSH.md for git init / push steps")
    print("=" * 72)


if __name__ == "__main__":
    main()
